### ISSUE TITLE
🐞 - Android 8.1 mask double character glitch

### ISSUE THREAD

**Issue by superlazycoder** [taiga-family/maskito#1444] opened 2024-08-14 06:47 UTC
### Which package(s) are the source of the bug?

@maskito/angular

### Playground Link

https://youtu.be/bBn9zYWMjUo

### Description

this application runs on android 8.0 and 8.1 and has these issues. Running on newer android devices it does not seem to have these issues. 

I attempted to disable the autocomplete and autocorrect on the inputs but that did not solve anything. 

When I have a maskito mask that has a non typed character, the correction will duplicate the number pressed when the space is added.

The phone number will start with +1 which does duplicate the 1 but that is because a 1 is allowed. However any other number 

the dollar text field demonstrates the decimal and will duplicate both after the $ and after the .

### Maskito version

3.0.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [X] Android

**Comment by nsbarsukov** [comment] 2024-08-14 10:30
@superlazycoder Hello!

Create reproduction using StackBlitz, please
https://maskito.dev/stackblitz

**Comment by nsbarsukov** [comment] 2024-08-14 10:31
Also, explore this plugin, please
https://maskito.dev/core-concepts/plugins#strict-composition

**Comment by superlazycoder** [comment] 2024-08-14 18:55
I have not been able to get the stackblitz share url to work on any machine. Much less the mobile device in question. 

these are the masks I use. 

const moneyOptions: MaskitoOptions = maskitoNumberOptionsGenerator({
  decimalZeroPadding: true,
  precision: 2,
  thousandSeparator: ',',
  decimalSeparator: '.',
  min: 0.0,
  max: 999.99,
  prefix: '$',
});

const phoneOptions: MaskitoOptions = {
  mask: [
    '+',
    '1',
    ' ',
    /[1-9]/,
    /\d/,
    /\d/,
    ' ',
    /\d/,
    /\d/,
    /\d/,
    ' ',
    /\d/,
    /\d/,
    /\d/,
    /\d/,
  ],
};

each time the field reaches a static character, it doubles the input. 

I have tried the strict composition, which is a fix for the autocomplete. It did not solve the issue. 

I attempted originally to disable the autocomplete, and that did not fix the issue. 

The only fields with the duplicate data are the ones with maskito masks on. And only on the older android operating systems. Unfortunately I am stuck with the operating systems.

Without being able to get the stackblitz link to work anywhere other than the original embeded window, the page does not afford me the ability to test it on my machine. 

This is the link nonetheless. https://maskito-starter-fallback-7ubvmb.stackblitz.io/

**Comment by nsbarsukov** [comment] 2024-08-19 08:23
@superlazycoder Hello!

I've tried some Androids – the bug is not reproducible.
I've used your StackBlitz and the following example from documentation 
https://maskito.dev/recipes/phone

___

**Samsung Galaxy Note 9**
**Android, v8.1**

https://github.com/user-attachments/assets/65f91cf3-ef32-48db-aab9-2786e4a3c669

___

**Samsung Galaxy S9**
**Android, v8.0**

https://github.com/user-attachments/assets/7e2c4052-ce77-4b09-b982-aaeb77f51849

**Comment by nsbarsukov** [comment] 2024-09-18 06:33
Closing this issue due to the lack of reproduction

**Closed by nsbarsukov** 2024-09-18 06:33 UTC
Labels: bug
