### ISSUE TITLE
🐞 - maskitoTransform returns undefined

### ISSUE THREAD

**Issue by rikusen0335** [taiga-family/maskito#1099] opened 2024-02-28 08:39 UTC
### Which package(s) are the source of the bug?

@maskito/core

### Playground Link

unfortunately nothing...

### Description

I am not digging down this behavior still, so I provide a short description:
We have the code like this:
```tsx
const Test = ({ defaultValue: _defaultValue, ...props }) => {
  const maskitoOptions = useMemo(
    () =>
      maskitoNumberOptionsGenerator({
        thousandSeparator,
      }),
    [thousandSeparator]
  )

  const ref = useMaskito({ options: maskitoOptions })

  const defaultValue = useMemo(
    () => maskitoTransform(_defaultValue?.toString() ?? '', maskitoOptions),
    [_defaultValue, maskitoOptions]
  )

  return <CustomInput {...props} ref={ref} defaultValue={defaultValue}>
}
```

In the local development, providing `3000 (Number)` to `maskitoTransform` will return `3,000 (String)`,
but in the staging, providing `3000 (Number)` will return `undefined`.

### Maskito version

2.0.2

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by nsbarsukov** [comment] 2024-02-28 09:11
@rikusen0335 Hello!
Unfortunately, without reproduction it is almost impossible for me to help you 😢 

`maskitoTransform` utility is harnessed by strict TypeScript.
And its signature does not contain `undefined`:
https://github.com/taiga-family/maskito/blob/5ac91a5d648bbce753cca0568b51ed66dbc81517/projects/core/src/lib/utils/transform.ts#L12-L15

Please, double check that in the runtime of the staging you don't provide `undefined`/`null` to `maskitoTransform`.

**Comment by rikusen0335** [comment] 2024-02-28 09:20
@nsbarsukov
Thank you for quick response!
Well yeah, there should be reproduction here but I have not investigate the issue, and I wanna place this just a note for someone met similar.

> Please, double check that in the runtime of the staging you don't provide `undefined`/`null` to `maskitoTransform`.

That is the weird point. Well, I am providing value with nullish coalescing operator (`foo ?? ''`) which should provide a value
(sorry, previously written code is wrong! Fixed it)

**Comment by nsbarsukov** [comment] 2024-03-27 08:17
@rikusen0335 Hello!

Unfortunately, I'm closing this issue because it does not have any reproduction.
If you reproduce it, feel free to open new issue!

**Closed by nsbarsukov** 2024-03-27 08:17 UTC
Labels: bug

**Comment by rikusen0335** [comment] 2024-03-27 16:59
Yeah sure
I just wanna make a note here
