### ISSUE TITLE
🐞 -  Ionic Input does not follow masking regex.

### ISSUE THREAD

**Issue by filipelle** [taiga-family/maskito#1434] opened 2024-08-06 15:43 UTC
### Which package(s) are the source of the bug?

@maskito/core, @maskito/angular

### Playground Link

not have one

### Description

In a Capacitor 6 / ionic 8 project I used the maskito directive with this regex:
```js
 readonly cardMask: MaskitoOptions = {
    mask: /^\d{1,4}(,\d*)?$/,
  };
```
The input was receiving the first 4 numbers then it would stop and shuffle the new number in.
I even tried a more elaborate regex:
`/^\d{1,4}|\d{1,4},|\d{1,4}(,\d*)?$/`

still the input would not let me insert a comma. The regexs work in a stackblitz, so i suppose there is a problem with field manipulation in angular.
Here is my input:
```html 
<ion-input
          type="number"
          formControlName="price"
          placeholder="Inserisci il prezzo"
          [maskito]="cardMask"
          label="Prezzo"
          labelPlacement="stacked"
></ion-input>```



### Maskito version

3.0.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [X] iOS
- [X] Android

**Comment by nsbarsukov** [comment] 2024-08-07 06:54
@filipelle Hello!

Provide reproduction (for example, github repository), please.
It's difficult to help you without it.


Also, attach video with you problem.

**Comment by nsbarsukov** [comment] 2024-08-07 07:09
I've created stackblitz with you described case (angular 17 + Ionic 8 + your mask):
https://stackblitz.com/edit/maskito-ionic-angular-1434

I can't reproduce you problem in it(

**Comment by nsbarsukov** [comment] 2024-08-19 08:25
Closing this issue due to the lack of reproduction.

Feel free to open a new issue again with the full reproduction of the problem.

**Closed by nsbarsukov** 2024-08-19 08:25 UTC
Labels: bug
